/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VISTA;

/**
 *
 * @author eddie
 */
public class Panel_GestionViajes extends javax.swing.JPanel {

    /**
     * Creates new form Panel_GestionViajes
     */
    public Panel_GestionViajes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPanelDinamico = new javax.swing.JScrollPane();
        PanelDinamico = new javax.swing.JPanel();
        TXTviaje_distancia = new javax.swing.JTextField();
        CBviaje_terminal_Llegada = new javax.swing.JComboBox<>();
        SPNviaje_precio = new javax.swing.JSpinner();
        CBviaje_terminal_Salida = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        TBLviajes = new javax.swing.JTable();
        BTN_eliminar_viajes = new javax.swing.JButton();
        BTN_nuevo_viajes = new javax.swing.JButton();
        BTN_guardar_viajes = new javax.swing.JButton();
        LBL_img_referencial = new javax.swing.JLabel();
        BTN_img_referencial = new javax.swing.JButton();
        DCviaje_fechaSalida = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LBLviaje_fechaLlegada = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LBLviaje_horaLlegada = new javax.swing.JLabel();
        SPNviaje_duracion = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SPNviaje_horaSalida = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LBL_viaje_ID = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        ScrollPanelDinamico.setBorder(null);
        ScrollPanelDinamico.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ScrollPanelDinamico.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ScrollPanelDinamico.setPreferredSize(new java.awt.Dimension(1060, 670));

        PanelDinamico.setBackground(new java.awt.Color(20, 20, 20));
        PanelDinamico.setPreferredSize(new java.awt.Dimension(1060, 670));
        PanelDinamico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TXTviaje_distancia.setBackground(new java.awt.Color(14, 14, 14));
        TXTviaje_distancia.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        TXTviaje_distancia.setForeground(new java.awt.Color(255, 255, 255));
        TXTviaje_distancia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TXTviaje_distancia.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 204, 0)));
        PanelDinamico.add(TXTviaje_distancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 100, 30));

        CBviaje_terminal_Llegada.setBackground(new java.awt.Color(14, 14, 14));
        CBviaje_terminal_Llegada.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        CBviaje_terminal_Llegada.setForeground(new java.awt.Color(255, 255, 255));
        CBviaje_terminal_Llegada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        CBviaje_terminal_Llegada.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(123, 216, 80)));
        CBviaje_terminal_Llegada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CBviaje_terminal_Llegada.setFocusable(false);
        PanelDinamico.add(CBviaje_terminal_Llegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 130, 30));

        SPNviaje_precio.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));
        SPNviaje_precio.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 204, 0)));
        SPNviaje_precio.setFocusable(false);
        PanelDinamico.add(SPNviaje_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 90, 30));

        CBviaje_terminal_Salida.setBackground(new java.awt.Color(14, 14, 14));
        CBviaje_terminal_Salida.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        CBviaje_terminal_Salida.setForeground(new java.awt.Color(255, 255, 255));
        CBviaje_terminal_Salida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        CBviaje_terminal_Salida.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(123, 216, 80)));
        CBviaje_terminal_Salida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelDinamico.add(CBviaje_terminal_Salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 130, 30));

        TBLviajes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        TBLviajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TBLviajes.setGridColor(new java.awt.Color(255, 255, 255));
        TBLviajes.getTableHeader().setResizingAllowed(false);
        TBLviajes.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(TBLviajes);

        PanelDinamico.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 670, 310));

        BTN_eliminar_viajes.setText("Eliminar");
        PanelDinamico.add(BTN_eliminar_viajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 610, 90, 30));

        BTN_nuevo_viajes.setText("Nuevo");
        PanelDinamico.add(BTN_nuevo_viajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 90, 30));

        BTN_guardar_viajes.setText("Guardar");
        PanelDinamico.add(BTN_guardar_viajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 610, 90, 30));

        LBL_img_referencial.setBackground(new java.awt.Color(0, 0, 0));
        LBL_img_referencial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        PanelDinamico.add(LBL_img_referencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 360, 250));

        BTN_img_referencial.setForeground(new java.awt.Color(255, 255, 255));
        BTN_img_referencial.setText("Imagen Referencial");
        BTN_img_referencial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 0)));
        BTN_img_referencial.setFocusable(false);
        PanelDinamico.add(BTN_img_referencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 120, 40));

        DCviaje_fechaSalida.setBackground(new java.awt.Color(0, 0, 0));
        DCviaje_fechaSalida.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 204, 0)));
        DCviaje_fechaSalida.setForeground(new java.awt.Color(255, 255, 255));
        DCviaje_fechaSalida.setDateFormatString("dd/MM/YYYY");
        DCviaje_fechaSalida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PanelDinamico.add(DCviaje_fechaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 130, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Terminal de Llegada");
        PanelDinamico.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 140, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Precio:");
        PanelDinamico.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 60, 30));

        LBLviaje_fechaLlegada.setBackground(new java.awt.Color(14, 14, 14));
        LBLviaje_fechaLlegada.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        LBLviaje_fechaLlegada.setForeground(new java.awt.Color(255, 255, 255));
        LBLviaje_fechaLlegada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelDinamico.add(LBLviaje_fechaLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 130, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hora de Salida:");
        PanelDinamico.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, 30));

        LBLviaje_horaLlegada.setBackground(new java.awt.Color(14, 14, 14));
        LBLviaje_horaLlegada.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        LBLviaje_horaLlegada.setForeground(new java.awt.Color(255, 255, 255));
        LBLviaje_horaLlegada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelDinamico.add(LBLviaje_horaLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 120, 30));

        SPNviaje_duracion.setModel(new javax.swing.SpinnerDateModel());
        SPNviaje_duracion.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 204, 0)));
        PanelDinamico.add(SPNviaje_duracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 120, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hora de Llegada:");
        PanelDinamico.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Duración Aproximada:");
        PanelDinamico.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, 30));

        SPNviaje_horaSalida.setModel(new javax.swing.SpinnerDateModel());
        SPNviaje_horaSalida.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(51, 204, 0)));
        PanelDinamico.add(SPNviaje_horaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 120, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha de Salida:");
        PanelDinamico.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 130, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha de Llegada:");
        PanelDinamico.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, 30));

        LBL_viaje_ID.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        LBL_viaje_ID.setForeground(new java.awt.Color(255, 255, 255));
        PanelDinamico.add(LBL_viaje_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 30, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Distancia:");
        PanelDinamico.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 80, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Terminal de Salida");
        PanelDinamico.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 150, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ID:");
        PanelDinamico.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 30, 30));

        ScrollPanelDinamico.setViewportView(PanelDinamico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollPanelDinamico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollPanelDinamico, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTN_eliminar_viajes;
    public javax.swing.JButton BTN_guardar_viajes;
    public javax.swing.JButton BTN_img_referencial;
    public javax.swing.JButton BTN_nuevo_viajes;
    public javax.swing.JComboBox<String> CBviaje_terminal_Llegada;
    public javax.swing.JComboBox<String> CBviaje_terminal_Salida;
    public com.toedter.calendar.JDateChooser DCviaje_fechaSalida;
    public javax.swing.JLabel LBL_img_referencial;
    public javax.swing.JLabel LBL_viaje_ID;
    public javax.swing.JLabel LBLviaje_fechaLlegada;
    public javax.swing.JLabel LBLviaje_horaLlegada;
    public javax.swing.JPanel PanelDinamico;
    public javax.swing.JSpinner SPNviaje_duracion;
    public javax.swing.JSpinner SPNviaje_horaSalida;
    public javax.swing.JSpinner SPNviaje_precio;
    public javax.swing.JScrollPane ScrollPanelDinamico;
    public javax.swing.JTable TBLviajes;
    public javax.swing.JTextField TXTviaje_distancia;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
