/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VISTA;

/**
 *
 * @author eddie
 */
public class Panel_Pasajeros extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Pasajeros
     */
    public Panel_Pasajeros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        RDBTNfem = new javax.swing.JRadioButton();
        RDBTNmasc = new javax.swing.JRadioButton();
        TxtApellidoMatePasa = new javax.swing.JTextField();
        TxtApellidoPatePasa = new javax.swing.JTextField();
        TxtNombrePasa = new javax.swing.JTextField();
        TxtEdadPasa = new javax.swing.JFormattedTextField();
        TxtDniPasa = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LblPrecioTotal = new javax.swing.JLabel();
        BTN_confirmar = new javax.swing.JButton();
        BTN_retroceder = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 670));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Z-Buss");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(123, 216, 80)));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 38, 140, -1));

        jScrollPane1.setBackground(new java.awt.Color(51, 255, 0));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 400));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pasajero Principal", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Consolas", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RDBTNfem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RDBTNfem.setForeground(new java.awt.Color(0, 0, 0));
        RDBTNfem.setText("Femenino");
        RDBTNfem.setFocusable(false);
        jPanel2.add(RDBTNfem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        RDBTNmasc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RDBTNmasc.setForeground(new java.awt.Color(0, 0, 0));
        RDBTNmasc.setText("Masculino");
        RDBTNmasc.setFocusable(false);
        jPanel2.add(RDBTNmasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        TxtApellidoMatePasa.setBackground(new java.awt.Color(255, 255, 255));
        TxtApellidoMatePasa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TxtApellidoMatePasa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        TxtApellidoMatePasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtApellidoMatePasaActionPerformed(evt);
            }
        });
        jPanel2.add(TxtApellidoMatePasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 280, 30));

        TxtApellidoPatePasa.setBackground(new java.awt.Color(255, 255, 255));
        TxtApellidoPatePasa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TxtApellidoPatePasa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        TxtApellidoPatePasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtApellidoPatePasaActionPerformed(evt);
            }
        });
        jPanel2.add(TxtApellidoPatePasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 280, 30));

        TxtNombrePasa.setBackground(new java.awt.Color(255, 255, 255));
        TxtNombrePasa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TxtNombrePasa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        TxtNombrePasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombrePasaActionPerformed(evt);
            }
        });
        jPanel2.add(TxtNombrePasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 260, 30));

        TxtEdadPasa.setBackground(new java.awt.Color(255, 255, 255));
        TxtEdadPasa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        TxtEdadPasa.setForeground(new java.awt.Color(0, 0, 0));
        try {
            TxtEdadPasa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(TxtEdadPasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 270, 30));

        TxtDniPasa.setBackground(new java.awt.Color(255, 255, 255));
        TxtDniPasa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        TxtDniPasa.setForeground(new java.awt.Color(0, 0, 0));
        try {
            TxtDniPasa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(TxtDniPasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 128, 270, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Asiento");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 90, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 98, 1000, 400));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Precio a Pagar:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 500, 150, 40));

        LblPrecioTotal.setFont(new java.awt.Font("Consolas", 1, 22)); // NOI18N
        LblPrecioTotal.setForeground(new java.awt.Color(0, 0, 0));
        LblPrecioTotal.setText("s/0000");
        add(LblPrecioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 510, 80, 30));

        BTN_confirmar.setBackground(new java.awt.Color(255, 255, 255));
        BTN_confirmar.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        BTN_confirmar.setForeground(new java.awt.Color(0, 0, 0));
        BTN_confirmar.setText("CONFIRMAR");
        BTN_confirmar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        BTN_confirmar.setFocusable(false);
        add(BTN_confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 570, 140, 40));

        BTN_retroceder.setBackground(new java.awt.Color(255, 255, 255));
        BTN_retroceder.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        BTN_retroceder.setForeground(new java.awt.Color(0, 0, 0));
        BTN_retroceder.setText("RETROCEDER");
        BTN_retroceder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        BTN_retroceder.setFocusable(false);
        add(BTN_retroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, 140, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void TxtApellidoMatePasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtApellidoMatePasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtApellidoMatePasaActionPerformed

    private void TxtApellidoPatePasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtApellidoPatePasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtApellidoPatePasaActionPerformed

    private void TxtNombrePasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombrePasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombrePasaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTN_confirmar;
    public javax.swing.JButton BTN_retroceder;
    public javax.swing.JLabel LblPrecioTotal;
    public javax.swing.JRadioButton RDBTNfem;
    public javax.swing.JRadioButton RDBTNmasc;
    public javax.swing.JTextField TxtApellidoMatePasa;
    public javax.swing.JTextField TxtApellidoPatePasa;
    public javax.swing.JFormattedTextField TxtDniPasa;
    public javax.swing.JFormattedTextField TxtEdadPasa;
    public javax.swing.JTextField TxtNombrePasa;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
